feat : 유저의 답변 리스트 조회 로직 추가
codestates-seb/seb40_main_004 pull request #208
Opened 2022-11-26 10:37 UTC by Tldkt

2022-11-26 11:53 UTC, yangddoddi reviewed
잘 읽었습니다~~ 아이디에 객체명을 붙여서 구별해주고 있기 때문에 likeCount에 굳이 asnwer를 다시 한 번 붙이지 않아도 될 것 같아요~~

2022-11-26 12:03 UTC, Shawn9948 requested changes
rest docs에 andexpect 응답값 확인 로직이 없는것 같습니다!

2022-11-26 12:03 UTC, Shawn9948 commented on server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/answer_controller/GetAnswerControllerTest.java
>                          document(
실제 값 확인하는  andExpect가 없는거같아요. 그리고 rest docs에 파라미터도 작성해주면 더 좋을것 같습니다.

2022-11-26 12:03 UTC, Shawn9948 commented on server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/answer_controller/GetAnswerControllerTest.java
> +                                responseFields(
헤더에 jwt가 필요하다고 requestHeader를 작성해주시면 좋을것같아요

2022-11-26 12:03 UTC, Shawn9948 commented on server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/answer_controller/GetAnswerControllerTest.java
> +                                responseFields(
파라미터도 ㅎㅎㅎㅎ

2022-11-26 12:13 UTC, Tldkt commented on server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/AnswerService.java
> +    int size = 5;
컨트롤러의 모든 요청에 대해 페이지네이션하여 응답하고 있습니다! 서비스 내의 모든 메서드가 getAllanswers(answerId,page, size)를 호출하다 보니 page, size값을 각 cud 메서드마다 설정하기보다 전역변수로 두는 것이 효율적이라고 생각했습니다:) 

default로 바꾼 건 오타네요 ㅋㅋㅋ 변수 선언 왜 한 거지 하고 지웠다가 되살린 거라 잘못 적었습니다. 수정해서 반영할게요!

2022-11-26 12:14 UTC, Tldkt commented on server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/mapper/AnswerMapper.java
> +    AnswerDto.ResponseUserAnswerList answerToResponseUserAnswerList(Answer answer,Boolean isPicked,Integer answerLikeCount,Integer commentCount );
처음에는 어색했는데 쓰다보니까 익숙해지는 것 같아요 ㅋㅋㅋ 감사합니다~~

2022-11-26 12:14 UTC, Tldkt commented on server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/answer_controller/GetAnswerControllerTest.java
> +                                responseFields(
OMG 매의 눈 감사합니다

2022-11-26 12:15 UTC, Tldkt commented
오 그렇네요! 게시글이랑 구분되도록 적은 건데 id에서 이미 구분이 되니 괜찮겠네요. 이 부분 수정해서 반영하겠습니다.

2022-11-27 09:30 UTC, Tldkt commented
> rest docs에 andexpect 응답값 확인 로직이 없는것 같습니다!

1. restdocs의 경우 목데이터를 확인하는 과정이라 통합테스트에서 대체하는 것으로 팀 내 컨벤션 수정이 되었습니다!
2. 말씀해주신 대로 헤더와 패스 파라미터 추가해서 수정했습니다! 감사해요:)

2022-11-27 10:37 UTC, merged