질문 리스트 조회 기능 구현
codestates-seb/seb40_main_004 pull request #292
Opened 2022-12-01 04:09 UTC by HA-SEUNG-JEONG

- 질문 리스트 전체 조회 완료했습니다.
- 로그인,회원가입 폼 스타일 수정 완료했습니다.
- 질문 리스트 정렬도 추가로 작업 에정입니다.
- 질문 검색 및 태그로 질문 검색하는 부분은 기능 구현 후에 UI 수정할 예정입니다.

2022-12-01 05:42 UTC, HyeonWooGa approved these changes
확인했습니다!

2022-12-01 06:47 UTC, HyeonWooGa requested changes
`lib/interfaces` 부분 변경 필요합니다

2022-12-01 06:53 UTC, hyejj19 requested changes

2022-12-01 06:53 UTC, hyejj19 commented on client/libs/interfaces.ts
> -export interface Tags {
사용하고 있는 interface라서 삭제, 수정하시면 전체적으로 에러납니다. 복구부탁드려요~

2022-12-02 02:17 UTC, hyejj19 approved these changes

2022-12-02 02:22 UTC, HyeonWooGa approved these changes

2022-12-02 02:23 UTC, merged