짜잘한 최적화 작업
codestates-seb/seb40_main_004 pull request #415
Opened 2022-12-16 11:12 UTC by HA-SEUNG-JEONG

- Image 컴포넌트에 alt attribute 적용
- button 태그에 명시적으로 `button`이라는 type 적용(참고: https://nykim.work/96)
- label 태그 적용
- twitter 및 facebook에서 제공하는 메타 태그 적용

2022-12-16 15:19 UTC, HyeonWooGa requested changes
제가 작업한 코드 사전 대화나 협의 없이 수정하신게 저의 상식과는 다르지만 우선 코드 수정하신 부분에 대해 코드리뷰 달았습니다. 전체적으로 하승님이 수정한 부분 다시 수정 필요하니 롤백해주시고 제가 다시 수정하겠습니다.

2022-12-16 15:19 UTC, HyeonWooGa commented on client/components/yeonwoo/SearchBar.tsx
> +        className="w-[80%] border border-solid border-font-gray rounded-full pl-2"
사전 협의 없이 스타일 변경하신 부분 반려하겠습니다

2022-12-16 15:19 UTC, HyeonWooGa commented on client/components/yeonwoo/SearchBar.tsx
> +      <button type="button">
해당 부분이 `<button type="button">` 이 되면 리액트폼 onSubmit 기반으로 되어있는 검색 로직이 버튼 클릭시 동작하지 않습니다 기존으로 롤백해야합니다

2022-12-17 05:33 UTC, HA-SEUNG-JEONG commented on client/components/yeonwoo/SearchBar.tsx
> +      <button type="button">
type 부분 삭제했습니다

2022-12-17 05:36 UTC, HA-SEUNG-JEONG commented on client/components/yeonwoo/SearchBar.tsx
> +      <label htmlFor="검색" className="mr-3">
일단 label에 태그에 있는 htmlFor 같은 경우는 협의를 통해 정해야 할 거 같아서 우선은 지웠습니다

2022-12-17 05:43 UTC, HA-SEUNG-JEONG commented on client/components/yeonwoo/HallOfFame.tsx
> +                        alt="rank"
의견 주신대로 수정했습니다

2023-01-06 12:33 UTC, closed without merging